/*
Usuario: ADMIN
Fecha: 2024-03-20
Propósito: Crear estructura de tablas para Octofit Tracker
Descripción: Script para crear todas las tablas necesarias para la aplicación Octofit Tracker
*/

-- Tabla de Usuarios
CREATE TABLE T_USERS (
    USR_ID NUMBER PRIMARY KEY,
    USR_USERNAME VARCHAR2(150) NOT NULL UNIQUE,
    USR_EMAIL VARCHAR2(254) NOT NULL UNIQUE,
    USR_PASSWORD VARCHAR2(255) NOT NULL,
    USR_FIRST_NAME VARCHAR2(100),
    USR_LAST_NAME VARCHAR2(100),
    USR_HEIGHT_CM NUMBER(5,2),
    USR_WEIGHT_KG NUMBER(5,2),
    USR_AGE NUMBER(3),
    USR_GENDER VARCHAR2(10),
    USR_FITNESS_LEVEL VARCHAR2(50),
    USR_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USR_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USR_LAST_LOGIN TIMESTAMP,
    USR_IS_ACTIVE NUMBER(1) DEFAULT 1
);

COMMENT ON TABLE T_USERS IS 'Tabla de perfiles de usuarios del sistema';
COMMENT ON COLUMN T_USERS.USR_ID IS 'Identificador único del usuario';
COMMENT ON COLUMN T_USERS.USR_USERNAME IS 'Nombre de usuario único';
COMMENT ON COLUMN T_USERS.USR_EMAIL IS 'Correo electrónico del usuario';
COMMENT ON COLUMN T_USERS.USR_PASSWORD IS 'Contraseña hasheada del usuario';
COMMENT ON COLUMN T_USERS.USR_HEIGHT_CM IS 'Altura del usuario en centímetros';
COMMENT ON COLUMN T_USERS.USR_WEIGHT_KG IS 'Peso del usuario en kilogramos';
COMMENT ON COLUMN T_USERS.USR_FITNESS_LEVEL IS 'Nivel de aptitud física (beginner, intermediate, advanced)';
COMMENT ON COLUMN T_USERS.USR_IS_ACTIVE IS 'Indica si el usuario está activo (1=activo, 0=inactivo)';

-- Tabla de Equipos
CREATE TABLE T_TEAMS (
    TEM_ID NUMBER PRIMARY KEY,
    TEM_NAME VARCHAR2(200) NOT NULL UNIQUE,
    TEM_DESCRIPTION VARCHAR2(1000),
    TEM_LEADER_ID NUMBER NOT NULL REFERENCES T_USERS(USR_ID),
    TEM_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TEM_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TEM_MEMBER_COUNT NUMBER DEFAULT 1,
    TEM_IS_ACTIVE NUMBER(1) DEFAULT 1
);

COMMENT ON TABLE T_TEAMS IS 'Tabla de equipos para competencias';
COMMENT ON COLUMN T_TEAMS.TEM_ID IS 'Identificador único del equipo';
COMMENT ON COLUMN T_TEAMS.TEM_NAME IS 'Nombre del equipo';
COMMENT ON COLUMN T_TEAMS.TEM_LEADER_ID IS 'ID del líder del equipo (referencia a T_USERS)';

-- Tabla de Miembros de Equipos
CREATE TABLE T_TEAM_MEMBERS (
    TMB_ID NUMBER PRIMARY KEY,
    TMB_TEAM_ID NUMBER NOT NULL REFERENCES T_TEAMS(TEM_ID),
    TMB_USER_ID NUMBER NOT NULL REFERENCES T_USERS(USR_ID),
    TMB_JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TMB_ROLE VARCHAR2(50) DEFAULT 'MEMBER',
    UNIQUE(TMB_TEAM_ID, TMB_USER_ID)
);

COMMENT ON TABLE T_TEAM_MEMBERS IS 'Tabla de relación entre usuarios y equipos';
COMMENT ON COLUMN T_TEAM_MEMBERS.TMB_TEAM_ID IS 'ID del equipo';
COMMENT ON COLUMN T_TEAM_MEMBERS.TMB_USER_ID IS 'ID del usuario';
COMMENT ON COLUMN T_TEAM_MEMBERS.TMB_ROLE IS 'Rol del miembro en el equipo (MEMBER, COACH)';

-- Tabla de Actividades
CREATE TABLE T_ACTIVITIES (
    ACT_ID NUMBER PRIMARY KEY,
    ACT_USER_ID NUMBER NOT NULL REFERENCES T_USERS(USR_ID),
    ACT_TYPE VARCHAR2(100) NOT NULL,
    ACT_NAME VARCHAR2(200) NOT NULL,
    ACT_DURATION_MINUTES NUMBER,
    ACT_DISTANCE_KM NUMBER(6,2),
    ACT_CALORIES_BURNED NUMBER,
    ACT_INTENSITY_LEVEL VARCHAR2(50),
    ACT_NOTES VARCHAR2(1000),
    ACT_PERFORMED_AT TIMESTAMP,
    ACT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACT_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE T_ACTIVITIES IS 'Tabla de actividades físicas registradas';
COMMENT ON COLUMN T_ACTIVITIES.ACT_ID IS 'Identificador único de la actividad';
COMMENT ON COLUMN T_ACTIVITIES.ACT_USER_ID IS 'ID del usuario que realizó la actividad';
COMMENT ON COLUMN T_ACTIVITIES.ACT_TYPE IS 'Tipo de actividad (Running, Cycling, Swimming, etc)';
COMMENT ON COLUMN T_ACTIVITIES.ACT_INTENSITY_LEVEL IS 'Nivel de intensidad (LOW, MEDIUM, HIGH)';

-- Tabla de Leaderboard
CREATE TABLE T_LEADERBOARD (
    LDB_ID NUMBER PRIMARY KEY,
    LDB_WEEK_ID VARCHAR2(10) NOT NULL,
    LDB_USER_ID NUMBER NOT NULL REFERENCES T_USERS(USR_ID),
    LDB_POINTS NUMBER DEFAULT 0,
    LDB_ACTIVITIES_COUNT NUMBER DEFAULT 0,
    LDB_TOTAL_DURATION_MINUTES NUMBER DEFAULT 0,
    LDB_TOTAL_CALORIES NUMBER DEFAULT 0,
    LDB_RANK NUMBER,
    LDB_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LDB_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(LDB_WEEK_ID, LDB_USER_ID)
);

COMMENT ON TABLE T_LEADERBOARD IS 'Tabla de clasificación competitiva semanal';
COMMENT ON COLUMN T_LEADERBOARD.LDB_WEEK_ID IS 'ID de la semana (formato YYYY-WW)';
COMMENT ON COLUMN T_LEADERBOARD.LDB_POINTS IS 'Puntos totales del usuario en la semana';
COMMENT ON COLUMN T_LEADERBOARD.LDB_RANK IS 'Posición en el ranking de la semana';

-- Tabla de Recomendaciones de Entrenamientos
CREATE TABLE T_RECOMMENDATIONS (
    REC_ID NUMBER PRIMARY KEY,
    REC_USER_ID NUMBER NOT NULL REFERENCES T_USERS(USR_ID),
    REC_TYPE VARCHAR2(100) NOT NULL,
    REC_TITLE VARCHAR2(200) NOT NULL,
    REC_DESCRIPTION VARCHAR2(2000),
    REC_INTENSITY VARCHAR2(50),
    REC_ESTIMATED_DURATION_MINUTES NUMBER,
    REC_REASON VARCHAR2(500),
    REC_STATUS VARCHAR2(50) DEFAULT 'PENDING',
    REC_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REC_VIEWED_AT TIMESTAMP,
    REC_ACCEPTED_AT TIMESTAMP
);

COMMENT ON TABLE T_RECOMMENDATIONS IS 'Tabla de recomendaciones personalizadas de entrenamientos';
COMMENT ON COLUMN T_RECOMMENDATIONS.REC_ID IS 'Identificador único de la recomendación';
COMMENT ON COLUMN T_RECOMMENDATIONS.REC_TYPE IS 'Tipo de recomendación (Workout, Rest, Recovery)';
COMMENT ON COLUMN T_RECOMMENDATIONS.REC_STATUS IS 'Estado (PENDING, VIEWED, ACCEPTED, REJECTED)';

-- Crear secuencias para auto-increment
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TEAMS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TEAM_MEMBERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACTIVITIES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEADERBOARD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECOMMENDATIONS START WITH 1 INCREMENT BY 1;

-- Crear índices para mejorar el rendimiento
CREATE INDEX IDX_USERS_EMAIL ON T_USERS(USR_EMAIL);
CREATE INDEX IDX_USERS_USERNAME ON T_USERS(USR_USERNAME);
CREATE INDEX IDX_ACTIVITIES_USER ON T_ACTIVITIES(ACT_USER_ID);
CREATE INDEX IDX_ACTIVITIES_DATE ON T_ACTIVITIES(ACT_PERFORMED_AT);
CREATE INDEX IDX_TEAM_MEMBERS_USER ON T_TEAM_MEMBERS(TMB_USER_ID);
CREATE INDEX IDX_TEAM_MEMBERS_TEAM ON T_TEAM_MEMBERS(TMB_TEAM_ID);
CREATE INDEX IDX_LEADERBOARD_WEEK ON T_LEADERBOARD(LDB_WEEK_ID);
CREATE INDEX IDX_LEADERBOARD_USER ON T_LEADERBOARD(LDB_USER_ID);
CREATE INDEX IDX_RECOMMENDATIONS_USER ON T_RECOMMENDATIONS(REC_USER_ID);

COMMIT;
